site:
    title:        My new site
    description:  Is awesome
    author_name:  You name here
    author_email: Your email here
    author_url:   Your url here

engine:
    themes: %dir%/vendor/carew/theme-bootstrap
    extensions:
        - Carew\Plugin\Toc\TocExtension
        - Carew\Plugin\Highlight\HighlightExtension
