site:
    title:        My new site
    description:  Is awesome
    author_name:  You name here
    author_email: Your email here
    author_url:   Your url here
    url_absolute: http://exemple.com

engine:
    themes:
        - %dir%/vendor/carew/theme-bootstrap
